version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/api
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    ports:
      - "80:3000"
    command: npm run dev
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projeto_extensao
    networks:
      - minha-rede

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_extensao
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - minha-rede

volumes:
  mysql-data:

networks:
  minha-rede:
