version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: ../Dockerfile  # Volta um nível para encontrar o Dockerfile
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: meu_banco
    networks:
      - minha-rede

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - minha-rede

volumes:
  mysql-data:

networks:
  minha-rede:
